### Create author
POST http://localhost:8080/api/authors
Content-Type: application/json
Accept: application/json

{
  "name": "Móra Ferenc"
}

### Get all authors
GET http://localhost:8080/api/authors
Accept: application/json

### Create book
POST http://localhost:8080/api/books/1
Content-Type: application/json
Accept: application/json

{
  "isbn": "12346",
  "title": "Ida regénye"
}

### Get books from one author
GET http://localhost:8080/api/books/1
Accept: application/json

### Get author with books
GET http://localhost:8080/api/authors/1
Accept: application/json

### Get Book by title fragment
GET http://localhost:8080/api/books?titleFragment=r












