POST http://localhost:8080/api/movies/2/ratings
Content-Type: application/json

{"rating": 11}

###
GET http://localhost:8080/api/movies/6
Accept: application/json

###
POST http://localhost:8080/api/movies
Content-Type: application/json

{
  "title": "Jurassic Park",
  "length": -1
}

### Get Ratings
GET http://localhost:8080/api/movies/1
Accept: application/json


###
PUT http://localhost:8080/api/movies/1
Content-Type: application/json

{
  "title": "",
  "length": 129
}